name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npm run test
